<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DESKTOP-4QS4J19" failures="2" tests="3" name="Default test(failed)" time="0.108" errors="0" timestamp="2022-04-15T13:00:24 IST">
  <testcase classname="Assertion.FailedTest" name="test6" time="0.021">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at Assertion.FailedTest.test6(FailedTest.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test6 -->
  <testcase classname="Assertion.FailedTest" name="test2" time="0.004">
    <failure type="java.lang.AssertionError" message="Print test2 When test case will fail expected [200] but found [300]">
      <![CDATA[java.lang.AssertionError: Print test2 When test case will fail expected [200] but found [300]
at Assertion.FailedTest.test2(FailedTest.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="Assertion.FailedTest" name="test4" time="0.006"/>
  <testcase classname="Assertion.FailedTest" name="test3" time="0.0">
    <ignored/>
  </testcase> <!-- test3 -->
  <testcase classname="Assertion.FailedTest" name="test5" time="0.0">
    <ignored/>
  </testcase> <!-- test5 -->
  <testcase classname="Assertion.FailedTest" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
